# build stage
FROM golang:alpine AS build-env
ADD . /src
RUN cd /src && go build -o bettertomorrow

# final stage
FROM alpine
WORKDIR /app
COPY --from=build-env /src/bettertomorrow /app/
EXPOSE 8080
ENTRYPOINT ./bettertomorrow